title: Produkt
nav:
    - index.md
    - Mini-KVM:
        - minikvm/index.md
        - minikvm/whats-in-the-box.md
        - minikvm/features.md
        - ../app/basic.md
        - minikvm/how-to-connect.md
        - Wie es funktioniert: /faq/usbkvm/kvm-over-usb/
        - Bewertungen & Presse: minikvm/reviews.md
        - minikvm/specifications.md
        - minikvm/usb-switch.md
        - minikvm/extension-pins.md
        - FAQs & Fehlersuche: /faq/minikvm/op-minikvm/
        - Warum Openterface: /faq/usbkvm/openterface/
    - Zubehör:
        - accessories/index.md
        - VGA zu HDMI Kabel 1m: accessories/vga-to-hdmi-cable.md
        - Type-C zu C Kabel Nylon 1.5m: accessories/nylong-c-to-c-150.md
        - Type-C zu C Kabel Orange 1.5m: accessories/type-c-to-c-cable-with-adapter.md
        - Type-C zu A Kabel Schwarz 30cm: accessories/black-c-to-a-30.md
        - HDMI Kabel 30cm: accessories/hdmi-male-to-male-cable.md
        - Werkzeugtasche: accessories/openterface-toolkit-bag.md