authors:
  TechxArtisan:
    name: TechxArtisan Studio
    description: Ein kreatives Studio und eine Gemeinschaft von Technikbegeisterten.
    avatar: /images/txa-avatar.jpg

  Openterface:
    name: Openterface
    description: Hallo zusammen!
    avatar: /images/op-avatar.jpg